### ISSUE TITLE
Directional enrichment analysis

### ISSUE THREAD

**Issue by opain** [ksiewert/GCSC#3]
Hello,

Apologies for posting another issue, but this method is exciting. I hope it is useful.

I am wondering whether it is possible to consider the direction of the gene's association in the TWAS when testing for enrichment. For example, if I have a continuous gene property file indicating whether a drug induces up- or down-regulates a given gene, could I use GCSC to test whether the drug induces a gene expression signature concordant or discordant with the gene expression signature in my TWAS? This would be a useful tool for drug repositioning analysis.

I think it is not possible using GCSC since it is based on TWAS chi squares and corregulation scores, but I thought I should ask to be sure.

Many thanks,

Ollie

**Comment by ksiewert** [comment]
Hi Ollie. This is a great question! As is, GCSC doesn't have this capability because it relies on the squared TWAS chi-squares like you say. However, there is definitely room for future methodology that would allow it. If you're curious, there's another paper by our group that looks at heritability enrichment using signed annotations with GWAS instead of TWAS: [Detecting genome-wide directional effects of transcription factor binding on polygenic disease risk](https://www.nature.com/articles/s41588-018-0196-7).

**Comment by opain** [comment]
Hi Katie, Thank you for the reply. It is great that there is opportunity to extent your method to account for direction of effect. Thank you for highlighting the paper using directional SNP data. I will keep an eye out for further developments.
Best wishes,
Ollie
