### ISSUE TITLE
Co-expression increases TWAS association

### ISSUE THREAD

**Issue by descmo** [ksiewert/GCSC#4]
In this paper, the below explanation was methioned,
"GCSC determines that a gene set is enriched for disease heritability if genes with high co-regulation to the gene set have higher TWAS chi-square statistics".

I'd like to ask you why a gene whose expression is highly co-regulated with others has higher TWAS chi-statictics.(I recognized that higher TWAS chi-statictics means strong association with trait of interest.)

I'm looking forward to your response.

**Comment by ksiewert** [comment]
Hello! The more genes a gene is co-regulated with, the higher the probability that it's co-regulated with a gene whose expression is causal for a trait. 

For example, if gene A is co-regulated with zero other genes, it will only have a significant TWAS chi-squared stat if gene A itself is causal for the trait. In contrast, if gene A was co-regulated with gene B and gene C, then its TWAS chi-squared stat will tend to be significant if the expression of gene A, gene B, or gene C is causal. This is because all 3 genes will have correlated expression, so they will all appear associated with the trait even if only one of them is actually causal.

If you're familiar with how high LD SNPs tend to have higher GWAS chi-squared stats, it's a very similar concept.

**Comment by descmo** [comment]
Thank you for your response. Your answer is very clear!(The example of LD is to understand for me.)
